DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS booking;
DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS request;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email varchar(320),
    name  varchar(200),
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);
CREATE TABLE IF NOT EXISTS request
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  varchar(300)                            not null,
    created      TIMESTAMP WITHOUT TIME ZONE,
    requestor_id BIGINT,
    CONSTRAINT pk_request PRIMARY KEY (id),
    CONSTRAINT fk_request_to_user foreign key (requestor_id) references users (id)
);
CREATE TABLE IF NOT EXISTS item
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_name   varchar(100),
    description varchar(300),
    available   bool,
    owner_id    BIGINT,
    request_id  bigint                                  NULL,
    CONSTRAINT pk_item PRIMARY KEY (id),
    CONSTRAINT fk_items_to_users FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT fk_items_to_requests FOREIGN KEY (request_id) REFERENCES request (id)
);
CREATE TABLE IF NOT EXISTS booking
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date   TIMESTAMP WITHOUT TIME ZONE,
    item_id    BIGINT,
    booker_id  BIGINT,
    status     varchar(10),
    CONSTRAINT pk_booking PRIMARY KEY (id),
    CONSTRAINT fk_booking_to_item foreign key (item_id) references item (id),
    CONSTRAINT fk_booking_to_users foreign key (booker_id) references users (id)
);
CREATE TABLE IF NOT EXISTS comment
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created   TIMESTAMP WITHOUT TIME ZONE,
    text      varchar(300)                            NOT NULL,
    item_id   BIGINT,
    author_id BIGINT,
    CONSTRAINT pk_comment PRIMARY KEY (id),
    CONSTRAINT fk_comment_to_item foreign key (item_id) references item (id),
    CONSTRAINT fk_comment_to_user foreign key (author_id) references users (id)
);